BEGIN;
TRUNCATE ticket_history RESTART IDENTITY;
UPDATE tickets SET source_id=CASE id WHEN 101 THEN 1 WHEN 102 THEN 2 WHEN 103 THEN NULL WHEN 104 THEN 3 WHEN 105 THEN 1 END, updated_at=clock_timestamp();
COMMIT;
